### PR TITLE
Show cluster status on first render and fix bug preventing refreshing twice

### PR DESCRIPTION
**Pull request by lukew3**
A few parts to this pr:

* Display graphs on initial load
* Use model to populate updated data pushed to stream with job
* Move div with target id to partial, allowing stream to be refreshed more than once

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202301293514034) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by johrstrom — APPROVED** [review]
This is good. Can you add the config singleton next, so we can configure these TTLs.

**Comment by johrstrom** [comment]
I'll let you squash and merge if you like.

**Comment by lukew3** [comment]
> I'll let you squash and merge if you like.

I've never used squash before. How do you squash and merge?

**Comment by lukew3** [comment]
> I've never used squash before. How do you squash and merge?

Nvm, it's an option on the merge pull request button

**Pull request merged**
