### PR TITLE
Update App Inspector with Action Cable

### LINKED ISSUE #43: request through actioncable
I think we got hung up on REST and websockets precisely because they're different protocols.

What if the flow was more like REST controllers generate static pages and any updates are requested and published through websockets. 

I'm wondering what it would look like if we made requests through actionable in javascipt.

* handle the 'on change' event
* send a websocket message something like `{ action: 'replace', id: 'app_inspector_histogram' }` (IDK what the interface is here, but simplicity is good and maybe it's even just `{ action: 'run_this_function' }` and then we just call a `run_this_function` on the thing listening).
* The rails app responds to this message by broadcasting the replace message (much like the system status panels do now)

So the slider `'on change'` wouldn't make an HTTP request it'd send a websocket message that the rails app would then broadcast another.  So there's no (or at least less) bleed from HTTP -> web sockets. static page are requested & shown over HTTP and all updates happen through websockets.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202382969344883) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by lukew3**
Enable client to use websocket to request a new version of the histogram, which is replaced in the html. I'd say that I'm slightly leaning towards merging this, but would be okay discarding it as well. I was able to cut down a lot of template code shown in the railsguides, and I think the end solution is pretty clean. It seems to be a little bit faster than the turbo-streams http method as well. 
Closes #43

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202446569849790) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by gbsoftwaresolutions** [comment]
Websocket fails.  Not connecting to host.

Therefore data not updating when slider is adjusted.

image

image

**Comment by lukew3** [comment]
@gerald-byrket Hmm, I'm not sure. Maybe it's because you're on ondemand-test.osc.edu and I'm on ondemand.osc.edu. Or maybe you are missing the actioncable gem. Did you run `bin/setup`?

**Comment by gbsoftwaresolutions** [comment]
> @gerald-byrket Hmm, I'm not sure. Maybe it's because you're on `ondemand-test.osc.edu` and I'm on `ondemand.osc.edu`. Or maybe you are missing the actioncable gem or your server needs to be restarted. Did you run `bin/setup`?

Ran bin/setup, bundle install, am on your branch, etc, etc, etc.

**Comment by lukew3** [comment]
@gerald-byrket Tested it and it works if you're visiting it from `ondemand.osc.edu` but not if you are on `ondemand-test.osc.edu`.

**Comment by johrstrom** [comment]
@gbsoftwaresolutions let's hold on merging this. While it's good as it is, I actually don't know if it's the right pattern we want to follow.

The task was to see what it would look like - and this done that. I don't know if it's the pattern we should follow, but I have to admit it's less code than I thought it'd be.

At any rate - this is OK to just hold here for a bit while we all start to figure out what idiomatic Turbo looks like.

**Pull request closed without merging**
